### ISSUE TITLE
Nginx: Settings for testing in local network without domain

### ISSUE THREAD

**Issue by saschafoerster** [jprjr/docker-multistreamer#17]
Hi @jprjr! First of all thank you for this nice package. I was searching exactly for this for some months, but finally found it. It's exactly the use case I want to use. 
But I didn't get far. I watched the YouTube videos, I read and changed all config files and I can't get the multistreamer to work in my local network with docker for testing purposes. 
May it's this sentence, that causes my problems (but I am not so good at docker, that I understood it directly): 
> Things to know: 
> When you use container linking, Docker updates the /etc/hosts file with hostnames, but nginx ignores that file, and strictly looks up hosts via DNS.
So is it possible, that local testing is not possible? Or which config would be usefull then? 

This is the error message i get: 
```
user@server:~# curl -v http://localhost:8081
* Rebuilt URL to: http://localhost:8081/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8081 (#0)
> GET / HTTP/1.1
> Host: localhost:8081
> User-Agent: curl/7.52.1
> Accept: */*
> 
* Recv failure: Die Verbindung wurde vom Kommunikationspartner zurückgesetzt
* Curl_http_done: called premature == 1
* stopped the pause stream!
* Closing connection 0
curl: (56) Recv failure: Die Verbindung wurde vom Kommunikationspartner zurückgesetzt
```
So I guess something is listening to this port, but is not ready to answer me. :) 
The browser can't get a connection neither. 

And here is my last config-file: 

```
redisio:
  volumes:
   - /home/multistreamer/redis:/var/lib/redis:Z
postgresql:
  volumes:
   - /home/multistreamer/postgresql:/var/lib/postgresql:Z
  environment:
   - POSTGRES_USER=multistreamer
   - POSTGRES_PASS=password
multistreamer:
  ports:
   - "localhost:8081:8081"
   - "localhost:6667:6667"
   - "localhost:1935:1935"
  volumes:
   - /home/multistreamer/multistreamer:/etc/multistreamer:Z
   - ./htpasswd:/etc/htpasswd-auth-server:Z
  environment:
   MULTISTREAMER_APP_NAME: multistreamer
   MULTISTREAMER_LANG_ID: en_us
   MULTISTREAMER_AUTH_ENDPOINT: 
   MULTISTREAMER_SESSION_SECRET: 123456
   MULTISTREAMER_PUBLIC_HTTP_URL: http://localhost:8081
   MULTISTREAMER_PUBLIC_RTMP_URL: rtmp://localhost:1935
   MULTISTREAMER_RTMP_PREFIX: multistreamer
   MULTISTREAMER_HTTP_PREFIX: 
   MULTISTREAMER_PUBLIC_IRC_HOSTNAME: localhost
   MULTISTREAMER_PUBLIC_IRC_PORT: 6667
   MULTISTREAMER_TWITCH_CLIENT_ID: 
   MULTISTREAMER_TWITCH_CLIENT_SECRET: 
   MULTISTREAMER_TWITCH_INGEST_SERVER: 
   MULTISTREAMER_YOUTUBE_CLIENT_ID: 
   MULTISTREAMER_YOUTUBE_CLIENT_SECRET: 
   MULTISTREAMER_YOUTUBE_COUNTRY_CODE: 
   MULTISTREAMER_FACEBOOK_APP_ID: 
   MULTISTREAMER_FACEBOOK_APP_SECRET: 
   MULTISTREAMER_MIXER_CLIENT_ID: 
   MULTISTREAMER_MIXER_CLIENT_SECRET: 
   MULTISTREAMER_MIXER_INGEST_SERVER: 
   MULTISTREAMER_LOG_LEVEL: debug
   MULTISTREAMER_PUBLIC_IRC_SSL: 'false'
   MULTISTREAMER_SESSION_NAME: multistreamer
   MULTISTREAMER_LOQ_QUERIES: 'true'
   MULTISTREAMER_LOQ_REQUESTS: 'true'
   MULTISTREAMER_IRC_FORCE_JOIN: 'false'
   MULTISTREAMER_WORKER_PROCESSES: 1
   MULTISTREAMER_DNS_RESOLVER: 1.1.1.1:53 ipv6=off
   MULTISTREAMER_DICT_STREAMS_SIZE: 10m
   MULTISTREAMER_DICT_WRITERS_SIZE: 10m
   MULTISTREAMER_FFMPEG_MAX_ATTEMPTS: 3
   MULTISTREAMER_PING: 1m
   MULTISTREAMER_PING_TIMEOUT: 30s
   MULTISTREAMER_SHOW_VERSION: 'true'
   MULTISTREAMER_IRC_MOTD: |-
     Welcome to the Multistreamer IRC server!
     I hope you have fun.




```
